<a href="https://colab.research.google.com/github/sohelcr77/tensorflow_bootcamp/blob/main/00tensorflow_bootcamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf


# imported tensorflow as tf(alias)

# Now let's check the version of TF

print(tf.__version__)

2.18.0


In [4]:
# Now lets create our first tensor using  tf.constant()

scaler = tf.constant(7)
scaler



<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Now lets check the dimension of tensor(.ndim is used to find dimension)

scaler.ndim


0

In [6]:
# Now lets create vector tensor using  tf.constant()

vector = tf.constant([10,20])
vector



<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [7]:
# Now lets check the dimension of tensor(.ndim is used to find dimension)

vector.ndim


1

In [8]:
# Now lets create matrix tensor using  tf.constant()

matrix = tf.constant([[10,20],
                     [7,10]])
matrix



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [ 7, 10]], dtype=int32)>

In [9]:
# Now lets check the dimension of tensor(.ndim is used to find dimension)

matrix.ndim


2